version: 2

models:

  # =====================================
  # GLPI COMPUTERS
  # =====================================

  - name: stg_glpi_computers

    description: "Cleaned staging model for GLPI computers"

    columns:

      - name: unique_id
        description: "Composite technical key"
        tests:
          - not_null
          - unique

      - name: computer_id
        tests:
          - not_null

      - name: computer_uuid

      - name: has_uuid
        tests:
          - not_null

      - name: computer_name
        tests:
          - not_null

      - name: is_template
        tests:
          - not_null

      - name: is_deleted
        tests:
          - not_null

      - name: is_ocs_import
        tests:
          - not_null

      - name: source_year
        tests:
          - not_null
          - accepted_values:
              values: [2013, 2014, 2015]

      - name: source_system
        tests:
          - not_null
          - accepted_values:
              values:
                - GLPI

      - name: computer_type
        tests:
          - accepted_values:
              values:
                - template
                - real_machine